version: '3'

services:
  grafana:
    env_file:
      - .env
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    container_name: ${GRAFANA_SERVICE_NAME}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

  loki:
    env_file:
      - .env
    image: grafana/loki:latest
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - loki-data:/loki

volumes:
  grafana-data:
  loki-data:
