version: '3'

services:
  api:
    build: ./api/.
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./api/:/home/app
    container_name: ${API_SERVICE_NAME}
    depends_on:
      - grafana
      - loki

  grafana:
    env_file:
      - .env
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    container_name: ${GRAFANA_SERVICE_NAME}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - loki

  loki:
    env_file:
      - .env
    image: grafana/loki:latest
    ports:
      - "${LOKI_PORT}:3100"
    volumes:
      - loki-data:/loki
      - ./loki-config.yml:/etc/loki/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yml
    container_name: ${LOKI_SERVICE_NAME}

volumes:
  grafana-data:
  loki-data:
